/**
 * Auto-inject CatalogProductGallery spreads after each catalog_product_page
 * when the product carries additional photos (images[1..N]).
 *
 * Operator directive (대표님 2026-05-25 / 2026-05-26):
 *   1. magazine variant 에서는 첫 이미지가 hero 페이지, 나머지는 다음
 *      페이지(들)에 화보처럼 자동 추가.
 *   2. 2026-05-26 — editorial 뿐 아니라 grid · corporate 도 동일하게
 *      모든 제품의 사진이 기본적으로 전부 보이도록 자동 inject. 운영자가
 *      매 제품마다 gallery 블록을 수동으로 붙이는 워크플로우 폐기.
 *
 * 동작:
 * - catalog_product_page 면 starter style 무관하게 inject.
 * - product.images.length > 1 일 때만 (hero 외 추가 사진이 있을 때).
 * - 8 장씩 다음 spread 로 (max 4 spread 자동 — 33장 이상은 짤림).
 * - 운영자가 catalog_product_page 의 props.autoGallery 를 false 로
 *   명시하면 자동 생성 비활성. 또는 같은 productId 의 gallery 블록이
 *   이미 다음에 있으면 (운영자가 수동 추가했으면) 자동 inject 건너뜀.
 */

interface GenericSection {
  id: string;
  blockType: string;
  props: Record<string, unknown>;
  sortOrder?: number;
  isVisible?: boolean;
  styleOverrides?: unknown;
}

interface ResolvedProductLike {
  images?: Array<unknown>;
}

// Photos per spread depends on the product_page's style:
//   editorial = 8 (mosaic 1~8c variants).
//   grid / corporate = 4 (2×2 default grid; operator can re-pick 2x3 or
//     3x2 etc. on individual gallery blocks afterwards).
// 운영자 지시 2026-05-26: 모든 제품 사진이 다 보여야 함. 캡 제거 — spread
// 수는 사진 수에 맞게 무제한 생성. 예전 MAX_AUTO_SPREADS=4 + editorial
// max=3 조합으로 12장 넘어가면 잘리던 버그 fix.
const PHOTOS_PER_SPREAD_EDITORIAL = 8;
const PHOTOS_PER_SPREAD_GRID = 4;

/**
 * Insert auto-generated catalog_product_gallery sections into the
 * sections array. Returns a NEW array; never mutates input.
 *
 * @param sections - persisted catalog sections in render order
 * @param resolveProduct - sync map: productId → resolved product (with
 *   images). When undefined for a section, that page's auto-gallery is
 *   skipped (caller hasn't fetched the product yet).
 */
export function expandAutoGallerySpreads<S extends GenericSection>(
  sections: S[],
  resolveProduct: (productId: string) => ResolvedProductLike | null | undefined,
): S[] {
  const out: S[] = [];
  for (let i = 0; i < sections.length; i++) {
    const s = sections[i]!;
    out.push(s);
    if (s.blockType !== 'catalog_product_page') continue;
    const productId = s.props?.productId as string | undefined;
    if (!productId) continue;

    // Operator opt-out — props.autoGallery === false skips auto-inject.
    if (s.props?.autoGallery === false) continue;

    // 2026-05-26 — 운영자 지시. 모든 starter (editorial/grid/corporate)
    // 에서 제품 사진이 기본적으로 다 펼쳐져야 한다 → variant gate 제거.
    // gallery block 의 style prop 은 product_page 의 style 을 그대로
    // 물려받아 (아래 push 에서) 같은 starter 시각 언어로 렌더됨.

    // If the next section is ALREADY a gallery for the same product,
    // assume the operator placed it manually and skip auto-inject.
    const next = sections[i + 1];
    if (
      next &&
      next.blockType === 'catalog_product_gallery' &&
      next.props?.productId === productId
    ) {
      continue;
    }

    const product = resolveProduct(productId);
    const images = Array.isArray(product?.images) ? product!.images : [];
    if (images.length <= 1) continue; // no extras

    // photosPerSpread 는 starter style 마다 다름. editorial 은 mosaic 이
    // 최대 8장 처리 → 8장씩, grid/corporate 는 spread 안 2×2 그리드 →
    // 4장씩. style 미지정이면 editorial 디폴트.
    const styleProp = s.props?.style as string | undefined;
    const photosPerSpread = styleProp === 'grid' || styleProp === 'corporate'
      ? PHOTOS_PER_SPREAD_GRID
      : PHOTOS_PER_SPREAD_EDITORIAL;

    // Generate spreads. First spread starts at images[1] (skip hero).
    // 운영자 지시 2026-05-26: 캡 없이 사진 수에 맞게 spread 무제한 생성.
    const extras = images.length - 1;
    const spreadCount = Math.ceil(extras / photosPerSpread);
    for (let n = 0; n < spreadCount; n++) {
      const rangeStart = 1 + n * photosPerSpread;
      out.push({
        ...s,
        id: `${s.id}__auto-gallery-${n}`,
        blockType: 'catalog_product_gallery',
        props: {
          productId,
          // product_page 의 style 그대로 (grid 면 grid spread, corporate
          // 면 corporate spread, 미지정이면 editorial 디폴트). gallery 가
          // 같은 카탈로그의 starter 시각 언어를 유지하도록.
          style: s.props?.style ?? 'editorial',
          rangeStart,
          // Mark synthesized — admin canvas can show a "auto" badge
          // and storefront can skip TOC numbering for these if desired.
          __autoGenerated: true,
        },
        // Preserve sortOrder neighborhood so a manual reorder later
        // doesn't have to renumber the universe. The renderer just
        // walks the array in order anyway.
        sortOrder: undefined,
      } as S);
    }
  }
  return out;
}
